### ISSUE TITLE
Bug Import Dell Warranty

### ISSUE THREAD

**Issue by yfeasson** [InfotelGLPI/manufacturersimports#92] opened 2020-09-23 11:19 UTC
Hello,

The information provided by the plugin is not the same as on the website.

The import is OK but the recovered warranty only takes 1 year instead of 3 years.

![image](https://user-images.githubusercontent.com/71764957/94005691-e9f48e00-fd9e-11ea-9cff-d03f38581967.png)

![image](https://user-images.githubusercontent.com/71764957/94005791-15777880-fd9f-11ea-87af-2c01563c9dcd.png)

Version GLPI : 9.5.1
Version Plugin : 2.3.0

Best Regards,

**Comment by fralla2** [comment] 2020-11-18 16:07
Similar problem here : 

We have many computers from the same order that imports correctly but with different dates for warranty and length.
Screenshots 2 and 3 are from Dell warranty on they website, directly from the link created for that asset in GLPI.


![image](https://user-images.githubusercontent.com/38400135/99555001-d2481900-298d-11eb-8b02-dc7a5a25a167.png)

![image](https://user-images.githubusercontent.com/38400135/99555112-f277d800-298d-11eb-963f-3c31089e0b8c.png)

![image](https://user-images.githubusercontent.com/38400135/99555217-0faca680-298e-11eb-9aad-fe50fab9b1d2.png)

Thanks

**Comment by BernardDeSaedeleer** [comment] 2020-11-19 13:27
J'ai le même problème.

**Comment by Nicolas-ld** [comment] 2020-11-26 16:13
Bonjour,

Comment arrivez vous à faire fonctionner ce plugin ? Jen 'ai que des erreurs.
J'ai demandé une cle API à DELL mais je ne sais pas ce qu'il faut mettre dans la bonne zone
première partir de la clé, seconde partie entre parenthèse, tout ?

Merci de votre aide

![import Dell](https://user-images.githubusercontent.com/73946914/100373066-76733500-300a-11eb-994a-db5952e58d2e.png)

**Comment by enannos** [comment] 2020-12-30 09:13
Hello everyone,

is this plugin working properly by default?
Or is there a need for "tweaking"? 
We do not get the above page.

Thanks

**Comment by MarcSamD** [comment] 2021-01-21 07:32
Like you can see on Fralla's screenshot, this issue is because a single computer (service tag) has multiple warranties (service), so the plugin will only recover one of the warranty (knowing the order of the warranty list returned by Dell API can change, so the result you get from the import will also change between computers or from time to time).

If you query Dell API (with a Powershell script for example), you can get a JSON file with different **entitlements**, as below.
So a "smart" GLPI plugin would be able to get all the different **itemNumber**, or maybe allow filterting on **serviceLevelDescription**, or maybe just recover the warranty with the latest **endDate**.

> {
    "id":  1111111,
    "serviceTag":  "12AB345",
    "orderBuid":  2222,
    "shipDate":  "2020-05-10T19:00:00Z",
    "productCode":  "3333",
    "localChannel":  "SMB",
    "productId":  "latitude-13-5300-laptop",
    "productLineDescription":  "LATITUDE 5300",
    "productFamily":  "Unknown",
    "systemDescription":  "Latitude 5300",
    "productLobDescription":  "Latitude",
    "countryCode":  "CN",
    "duplicated":  false,
    "invalid":  false,
    "entitlements":  [
                         {
                             "itemNumber":  "4444",
                             "startDate":  "2020-05-09T19:00:00.298Z",
                             "endDate":  "2021-05-10T18:59:59.303Z",
                             "entitlementType":  "INITIAL",
                             "serviceLevelCode":  "IF",
                             "serviceLevelDescription":  "Information SKU",
                             "serviceLevelGroup":  11
                         },
                         {
                             "itemNumber":  "5555",
                             "startDate":  "2020-05-09T19:00:00.552Z",
                             "endDate":  "2021-05-10T18:59:59.558Z",
                             "entitlementType":  "INITIAL",
                             "serviceLevelCode":  "JA",
                             "serviceLevelDescription":  "Onsite Service After Remote Diagnosis",
                             "serviceLevelGroup":  5
                         },
                         {
                             "itemNumber":  "6666",
                             "startDate":  "2020-05-09T19:00:00.046Z",
                             "endDate":  "2021-05-10T18:59:59.052Z",
                             "entitlementType":  "INITIAL",
                             "serviceLevelCode":  "RB",
                             "serviceLevelDescription":  "Carry-in Svc/Return to Base",
                             "serviceLevelGroup":  5
                         },
                         {
                             "itemNumber":  "7777",
                             "startDate":  "2021-05-10T19:00:00.791Z",
                             "endDate":  "2023-05-11T18:59:59.796Z",
                             "entitlementType":  "EXTENDED",
                             "serviceLevelCode":  "JA",
                             "serviceLevelDescription":  "Onsite Service After Remote Diagnosis",
                             "serviceLevelGroup":  5
                         }
                     ]
}

**Comment by MarcSamD** [comment] 2021-01-21 08:32
I just checked dell.class.php and indeed this case is supposed to be supported by the plugin:

>    /**
    * @see PluginManufacturersimportsManufacturer::getWarrantyInfo()
    */
   function getWarrantyInfo($contents) {
      $info = json_decode($contents, true);
      // v5
      // **when several warranties are available, will take the last one**
      $max_date = false;
      $i = false;
      if (isset($info[0]['entitlements'])) {
         foreach ($info[0]['entitlements'] as $k => $d) {
            $date = new \DateTime($d['endDate']);
            if ($max_date == false || $date > $max_date) {
               $max_date = $date;
               $i        = $k;
            }
         }
      }
      if ($max_date && $i) {
         return $info[0]['entitlements'][$i]['serviceLevelDescription'];
      }
      return false;
   }

But for some reason, it is not working as expected :)

**Comment by MarcSamD** [comment] 2021-01-21 08:46
Probably a duplicate of https://github.com/InfotelGLPI/manufacturersimports/issues/90# that is closed but I still have the issue...

**Comment by MarcSamD** [comment] 2021-01-21 09:16
What a d... I'm doing everything in a reverse order today...
Just need to upgrade the plugin from version 2.3.0 to 2.3.1 which is fixing this issue as https://github.com/InfotelGLPI/manufacturersimports/issues/90
Issue [closed] on my side.

**Comment by enannos** [comment] 2021-01-21 16:16
No difference on my installation. 
I have just updated the plugin and I cannot see any difference.

**Comment by MarcSamD** [comment] 2021-01-22 02:00
@enannos You should open another issue with more details. "We do not get the above page." doesn't seem related to the import of Dell warranty (and is not detailed enough for anyone to help you).

**Comment by fralla2** [comment] 2021-01-22 14:42
Posted in issue #90 but since it's been closed, I copy it here....

"Dell Digital Delivery" should be discarded as a warranty information because it messes-up the dates...

See for example this asset :
https://www.dell.com/support/home/en-ca/product-support/servicetag/0-eFc3RkFLekZxYnBuMXlHbDBGbXpnUT090/overview#

![image](https://user-images.githubusercontent.com/38400135/105504634-fed22700-5c95-11eb-8625-1e90527b1d0a.png)

![image](https://user-images.githubusercontent.com/38400135/105504657-04c80800-5c96-11eb-9b97-06d32c636d1b.png)

It should have took the older date as the beginning date of the warranty (the one in green), not accounting for "Dell Digital Delivery" whom should be discarded to begin with, and the newest date for the end of warranty (because the total warranty is the combination of a few support levels contracts over the years)...

In all cases, it should discard the digital delivery as it's only covering for how long Dell would be providing downloads for drivers and softwares for this machine and not related to the hardware itself...

Also, a really big thanks for your good work, it's really appreciated.

Francois

**Comment by tsmr** [comment] 2021-09-30 11:44
Corrected on master

**Closed by tsmr** 2021-09-30 11:44 UTC
